// app/components/visualizer/BeforeAfterSlider.vue
<script setup lang="ts">
const visualizerStore = useVisualizerStore()
const { sliderPosition, showBeforeAfter } = storeToRefs(visualizerStore)

const sliderRef = ref<HTMLDivElement | null>(null)
const trackRef = ref<HTMLDivElement | null>(null)
const isDragging = ref(false)

function startDrag(e: MouseEvent | TouchEvent) {
  isDragging.value = true
  e.preventDefault()
  window.addEventListener('mousemove', onMove)
  window.addEventListener('mouseup', stopDrag)
  window.addEventListener('touchmove', onMove, { passive: false })
  window.addEventListener('touchend', stopDrag)
}

function onMove(e: MouseEvent | TouchEvent) {
  if (!isDragging.value || !trackRef.value) return
  const rect = trackRef.value.getBoundingClientRect()
  const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX
  const pos = Math.min(100, Math.max(0, ((clientX - rect.left) / rect.width) * 100))
  visualizerStore.setSliderPosition(pos)
}

function stopDrag() {
  isDragging.value = false
  window.removeEventListener('mousemove', onMove)
  window.removeEventListener('mouseup', stopDrag)
  window.removeEventListener('touchmove', onMove)
  window.removeEventListener('touchend', stopDrag)
}

onUnmounted(stopDrag)
</script>

<template>
  <div ref="trackRef" class="absolute inset-0 z-10 select-none"
    :class="showBeforeAfter ? 'cursor-ew-resize' : 'pointer-events-none'"
    @mousedown="showBeforeAfter && startDrag($event)" @touchstart.prevent="showBeforeAfter && startDrag($event)">
    <!-- Divider line -->
    <div v-if="showBeforeAfter" class="absolute top-0 bottom-0 w-0.5 bg-white shadow-lg"
      :style="{ left: `${sliderPosition}%` }">
      <!-- Handle -->
      <div ref="sliderRef"
        class="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-9 h-9 bg-white rounded-full shadow-elevated flex items-center justify-center cursor-ew-resize">
        <Icon name="lucide:move-horizontal" class="w-4 h-4 text-text-primary" />
      </div>

    </div>

    <!-- Labels fixed to container edges -->
    <div
      class="absolute top-3 left-3 text-white text-xs font-semibold bg-black/40 backdrop-blur-sm px-2 py-0.5 rounded-full pointer-events-none">
      Antes
    </div>
    <div
      class="absolute top-3 right-3 text-white text-xs font-semibold bg-black/40 backdrop-blur-sm px-2 py-0.5 rounded-full pointer-events-none">
      Después
    </div>
  </div>
</template>

// visualizard/components/visualizer/BeforeAfterSlider.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import Image from 'next/image';
import { ChevronLeft, ChevronRight } from 'lucide-react';

interface BeforeAfterSliderProps {
  beforeImage: string;
  afterImage: string;
}

export default function BeforeAfterSlider({ beforeImage, afterImage }: BeforeAfterSliderProps) {
  const [sliderPosition, setSliderPosition] = useState(50);
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const handleMove = (clientX: number) => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const x = Math.max(0, Math.min(clientX - rect.left, rect.width));
    const percent = Math.max(0, Math.min((x / rect.width) * 100, 100));
    setSliderPosition(percent);
  };

  const handleMouseMove = (e: MouseEvent) => {
    if (!isDragging) return;
    handleMove(e.clientX);
  };

  const handleTouchMove = (e: TouchEvent) => {
    if (!isDragging) return;
    handleMove(e.touches[0].clientX);
  };

  useEffect(() => {
    if (isDragging) {
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', () => setIsDragging(false));
      window.addEventListener('touchmove', handleTouchMove);
      window.addEventListener('touchend', () => setIsDragging(false));
    }
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', () => setIsDragging(false));
      window.removeEventListener('touchmove', handleTouchMove);
      window.removeEventListener('touchend', () => setIsDragging(false));
    };
  }, [isDragging]);

  return (
    <div 
      ref={containerRef}
      className="relative w-full aspect-[4/3] md:aspect-[16/9] overflow-hidden rounded-2xl select-none cursor-ew-resize shadow-card"
      onMouseDown={(e) => {
        setIsDragging(true);
        handleMove(e.clientX);
      }}
      onTouchStart={(e) => {
        setIsDragging(true);
        handleMove(e.touches[0].clientX);
      }}
    >
      {/* After Image (Background) */}
      <Image
        src={afterImage}
        alt="Después"
        fill
        className="object-cover"
        unoptimized
      />
      
      {/* Before Image (Foreground, clipped) */}
      <div 
        className="absolute inset-0 overflow-hidden"
        style={{ clipPath: `polygon(0 0, ${sliderPosition}% 0, ${sliderPosition}% 100%, 0 100%)` }}
      >
        <Image
          src={beforeImage}
          alt="Antes"
          fill
          className="object-cover"
          unoptimized
        />
      </div>

      {/* Labels */}
      <div className="absolute top-4 left-4 chip bg-black/50 text-white backdrop-blur-md border-none pointer-events-none">
        Antes
      </div>
      <div className="absolute top-4 right-4 chip bg-black/50 text-white backdrop-blur-md border-none pointer-events-none">
        Después
      </div>

      {/* Slider Handle */}
      <div 
        className="absolute top-0 bottom-0 w-1 bg-white cursor-ew-resize"
        style={{ left: `${sliderPosition}%`, transform: 'translateX(-50%)' }}
      >
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-10 h-10 bg-white rounded-full shadow-elevated flex items-center justify-center">
          <ChevronLeft className="w-4 h-4 text-text-secondary" />
          <ChevronRight className="w-4 h-4 text-text-secondary" />
        </div>
      </div>
    </div>
  );
}
